package centralcapturasjudicial.model.entity.contacorrente;


// Generated 16/03/2018 15:24:07 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;
/**
 * TabCcId generated by hbm2java
 */

@Embeddable
public class IdConta  implements java.io.Serializable {
    @Column(name="nr_age", nullable=false)
    private short nrAgencia;
    @Column(name="nr_cta", nullable=false)
    private long nrConta;

    public IdConta() {
    }

    public IdConta(short nrAge, long nrCta) {
       this.nrAgencia = nrAge;
       this.nrConta = nrCta;
    }

    /**
     * @return the nrAgencia
     */
    public short getNrAgencia() {
        return nrAgencia;
    }

    /**
     * @param nrAgencia the nrAgencia to set
     */
    public void setNrAgencia(short nrAgencia) {
        this.nrAgencia = nrAgencia;
    }

    /**
     * @return the nrConta
     */
    public long getNrConta() {
        return nrConta;
    }

    /**
     * @param nrConta the nrConta to set
     */
    public void setNrConta(long nrConta) {
        this.nrConta = nrConta;
    }
    
    

}


